### ISSUE TITLE
Is the path to Dockerfile incorrect for each workspace in GitHub Action?

### ISSUE THREAD

**Issue by YuZhong-Chen** [j3soon/ros2-agv-essentials#19]
I reviewed the action file in the repository yesterday and suspect there might be an issue with the file path.  
However, I haven't configured a GitHub Action before, so it could result from my misunderstanding.

https://github.com/j3soon/ros2-agv-essentials/blob/2d197a744495a0553820ad0d8e454119f8a84034/.github/workflows/build-template-ws.yaml#L3-L9

Should the path to the Dockerfile be: `template_ws/docker/Dockerfile` ?

**Comment by j3soon** [comment]
You are right. I will fix it soon, thank you!
